name: CI/CD Pipeline for NodeJS Demo App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ajay3502 }}/nodejs-demo-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ajay3502 }}
          password: ${{ secrets.Ajay3502@ }}

      - name: Push Docker Image
        run: docker push ${{ secrets. ajay3502 }}/nodejs-demo-app:latest
